/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * To learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.8/samples
 */
plugins {
    kotlin("jvm") version "2.0.0"
}
dependencies {
    implementation(kotlin("stdlib"))
    implementation(files("lib/SciBot-dependencies.jar"))
}
repositories {
    mavenCentral()
}